export const devicesList = [
  "Air conditioner",
  "Blender",
  "Ceiling Fan",
  "Clothes dryer",
  "Desk lamp",
  "Dishwasher",
  "Electric kettle",
  "Evaporative cooler",
  "Table Fan",
  "Food processor",
  "Freezer",
  "Hairdryer",
  "Heat pump control panel",
  "Humidifier",
  "Ice cream maker",
  "Iron",
  "Lights",
  "Lamp",
  "Lawn mower",
  "Microwave",
  "Radiator",
  "Refrigerator",
  "Rice cooker",
  "Sewing machine",
  "Space heater",
  "Stove",
  "TV",
  "Upright vacuum cleaner",
  "Vacuum cleaner",
  "Washing machine",
  "Water heater",
];
