export const GET_CURRENT_ROOM_DEVICES = "GET_CURRENT_ROOM_DEVICES";
export const GET_MY_DEVICES = "GET_MY_DEVICES";
export const ADD_DEVICE = "ADD_DEVICE";
export const SELECTED_DEVICE = "SELECTED_DEVICE";
