export const GET_CURRENT_ROOM_DEVICES = "GET_CURRENT_ROOM_DEVICES";
export const GET_MY_DEVICES = "GET_MY_DEVICES";
export const ADD_DEVICE = "ADD_DEVICE";
export const SELECTED_DEVICE = "SELECTED_DEVICE";
export const CHANGE_DEVICE_STATUS = "CHANGE_DEVICE_STATUS";
export const UPDATE_DEVICES = "UPDATE_DEVICES";
